/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import CourseCatalog.Course;
import CourseSchedule.CourseLoad;
import CourseSchedule.CourseOffer;
import CourseSchedule.CourseSchedule;
import CourseSchedule.SeatAssignment;
import Department.Department;
import Employer.EmployerDirectory;
import Employer.EmployerProfile;
import Faker.FakerUtl;
import Persona.EmploymentHistory.Employment;
import Persona.EmploymentHistory.EmploymentHistory;
import Persona.Faculty.FacultyDirectory;
import Persona.Person;
import Persona.PersonDirectory;
import Persona.StudentDirectory;
import Persona.StudentProfile;
import java.awt.CardLayout;
import java.awt.Container;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import jchart.LineChart_AWT;
import jchart.PieChart_AWT;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author Dengbowen
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Department department;
    StudentDirectory studentDirectory;
    CardLayout card;
    int[] repC1;
    int[] repC2;
    public MainJFrame() throws InterruptedException {
        department=generateData();
        studentDirectory=department.getStudentDirectory();       
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        SplitPane = new javax.swing.JSplitPane();
        contrlarea = new javax.swing.JPanel();
        btnStudentsProfile = new javax.swing.JButton();
        Analysis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        workarea = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStudentsProfile.setText("Students");
        btnStudentsProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsProfileActionPerformed(evt);
            }
        });

        Analysis.setText("Analysis");
        Analysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalysisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contrlareaLayout = new javax.swing.GroupLayout(contrlarea);
        contrlarea.setLayout(contrlareaLayout);
        contrlareaLayout.setHorizontalGroup(
            contrlareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contrlareaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contrlareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStudentsProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Analysis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contrlareaLayout.setVerticalGroup(
            contrlareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contrlareaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStudentsProfile)
                .addGap(52, 52, 52)
                .addComponent(Analysis)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(contrlarea);

        workarea.setMinimumSize(new java.awt.Dimension(800, 400));
        workarea.setLayout(new java.awt.CardLayout());
        SplitPane.setRightComponent(workarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentsProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsProfileActionPerformed

        StudentsJPanel studentsJPanel=new StudentsJPanel(studentDirectory,workarea);
        workarea.add("StudentsJPanel",studentsJPanel);
        CardLayout layout = (CardLayout)workarea.getLayout();
        layout.next(workarea);
        
    }//GEN-LAST:event_btnStudentsProfileActionPerformed

    private void AnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalysisActionPerformed
        // TODO add your handling code here:
        
        Analysis(studentDirectory);
    }//GEN-LAST:event_AnalysisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainJFrame().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analysis;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton btnStudentsProfile;
    private javax.swing.JPanel contrlarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel workarea;
    // End of variables declaration//GEN-END:variables

    private Department generateData() throws InterruptedException{
         Scanner sc = new Scanner(System.in);
        
        Department department = new Department("Information Systems");
        System.out.println("Department:"+department.getName());
        
//        //Create semesters
        String[] sems = new String[]{"Fall2019","Spring2020","Fall2020","Spring2021"};
        
        //16 courses
        String[][] courses = {{"INFO-5001","INFO-5100","INFO-6105","INFO-6210","INFO-6250","INFO-7110","INFO-7250",
                                "CSYE-5001","CSYE-5100","CSYE-6105","CSYE-6210","CSYE-6250","CSYE-7110","CSYE-7250","INFO-7245","INFO-7374"},
                                 {"AMD","AED","DS PYTHON","DS MEHOD","WEB DESGIN","PROGRAM STRUCTURE","DATA MANAGEMENT",
                                  "OOD","OOD C++","OS","SCALA","Foundations of Parallel","User Experience Design ","Advanced Game Analytics","Agile Software","Advanced User Experience"}   }; 
        for (int j = 0; j < courses[0].length; j++) {
                Course course = department.newCourse(courses[1][j], courses[0][j], 4);
        }
        //generate teacher
        PersonDirectory pd = department.getPersonDirectory();
        FacultyDirectory fd = department.getFacultydirectory();
        for (int i = 0; i < 12; i++) {
             Person person = pd.newPerson(""+(99503750+i),FakerUtl.name());
             fd.newStudentProfile(person);
        }
        //generate courseoffer by semester
        for (int i = 0; i < sems.length; i++) {
           CourseSchedule courseschedule = department.newCourseSchedule(sems[i]);
           int faculIdx = 0;
            for (int j = 0; j < courses[0].length; j++) {
               CourseOffer courseoffer = courseschedule.newCourseOffer(courses[0][j]);
               courseoffer.generatSeats(100);
               if(faculIdx>=fd.getTeacherlist().size()) faculIdx = 0;
               courseoffer.AssignAsTeacher(fd.getTeacherlist().get(faculIdx));
               faculIdx+=1;
            }
            System.out.println(courseschedule.toString());
        }

        System.out.println("generate 100 students.. Enter");
        String str;
         while((str = sc.nextLine()) !="")
          {
             break;
          }
       // generate 100 students
       
        StudentDirectory sd = department.getStudentDirectory();
        for (int i = 0; i < 100; i++) {
             Person person = pd.newPerson("00"+(15800+i),FakerUtl.name());
            StudentProfile student = sd.newStudentProfile(person);
//            System.out.println(student);
        }
        System.out.println("Done!");
        System.out.println("create companies and create employment for students.. Enter");
         while((str = sc.nextLine()) !="")
          {
             break;
          }
        
        //create companies
        EmployerDirectory employerDirectory=department.getEmployerDirectory();
        for (int i = 0; i < 20; i++) { //create n companies
            EmployerProfile emp = employerDirectory.newEmployerProfile(FakerUtl.company(),FakerUtl.randomIntNum(2,3), FakerUtl.randomIntNum(4, 5));  //name , weight, quality 把公司的权重比列降低
//            System.out.println(emp);
            for (int j = 0; j < 10; j++) { //create n jobs for each company
                Employment e = new Employment(FakerUtl.job(),FakerUtl.randomIntNum(3, 13),FakerUtl.randomIntNum(3, 13),emp);  //0-169
//                //string job,int weight,int quality,EmployerProfile employer
//        //creat relevant courses
                //改成如果分数高的话，相关课程会多一些, 每10分就有一节相关课程
                int index = e.getEmploymentGrade()/10; 
                if(index>16) index = 15;
                for (int k = 0; k < index; k++) { // 随机添加相关课程 
                    Course c = department.getCourseCatalog().getCourseByNumber(courses[0][k]);
                    e.newRelevantCourse(c);
                }
            }
           
        }

        
        //create employment for students
        for (StudentProfile stu : sd.getStudentlist()) {
            EmploymentHistory employmenthistory = stu.getEmploymenthistory();
            EmployerProfile oneEmployerProfile = employerDirectory.getOneEmployerProfile(); //随机拿一个公司
            int randomIntNum = FakerUtl.randomIntNum(1,5);
            for (int i = 0; i < randomIntNum; i++) {//随机插入1-5份工作
                Employment e =  employmenthistory.newEmployment(oneEmployerProfile.getEmployments().get(i));
//                System.out.println(e.getEmployerName()+"分数:"+e.getEmploymentGrade());
            }
        }
        
        System.out.println("student sorts by rank.. Enter");
        while((str = sc.nextLine()) !="")
         {
            break;
         }

        Collections.sort(sd.getStudentlist());
        
        //generate transcript for each student
        //every semester add 2 course offer
        //给所有学生添加课程和成绩
        //*****排在前面的人给他的分数都高一些*******
        double weight  = sd.getStudentlist().size();
        for (int k = 0; k < sd.getStudentlist().size(); k++) {
            StudentProfile stu = sd.getStudentlist().get(k);
            int courseIdx = 0;
            /*---------------------****-------------*/
            
            
            for (int i = 0; i < sems.length; i++) {
                CourseLoad courseload = stu.newCourseLoad(sems[i]); //给学生添加一个学期
                CourseSchedule courseschedule = department.getCourseSchedule(sems[i]); //获取部门内的某个学期课程数据
                //随机添加一门课，但不能添加重复的课程
                double bound = (weight-k)/weight;
                int b = (int) (bound*100);
                for (int j = 0; j < 2; j++) {
                    int cdx = FakerUtl.randomIntNum(1, 2);
                    if(courseIdx + cdx>15)
                    {
                       cdx = 1;
                    }
                    CourseOffer courseoffer = courseschedule.getCourseOfferByNumber(courses[0][courseIdx + cdx]); //获取该学期内的某节课
                    courseIdx += cdx;
                    SeatAssignment sa = courseload.newSeatAssignment(courseoffer); //给该学生添加这门课
                    int biggrade = FakerUtl.randomIntNum(200+b,300+b);
//                    System.out.println("分数=="+biggrade/100.0);
                    sa.setGrade(biggrade/100.0); //给这门课分数
                
                }
            }
//            System.out.println(stu.getPerson().getName()+" trans 课程：");
//            for(Course c:stu.getTranscript().getCourses()){
//                System.out.println(c);
//            }
            
        }
        
        System.out.println("Done!");

        

                

//         int index = 1;
//         for (StudentProfile stu : sd.getStudentlist()) {
//             System.out.println(String.format("%d    rank:{%d}    %s", index++,stu.getEmploymenthistory().getEmploymentGrade(),stu.getPerson()));
//         }
         
//relevant course number
        repC1 = new int[9]; //代表相关课程和个人选课的重复数目为0-8
        repC2 = new int[9];
        int stl = sd.getStudentlist().size();
        for (int i = 0; i < sd.getStudentlist().size(); i++) {
            StudentProfile stu =  sd.getStudentlist().get(i);
            ArrayList<Course> tcs = stu.getTranscript().getCourses();
            int num = stu.getEmploymenthistory().getSameCoursesNum(tcs);
            if(i<stl/2)
                repC1[num]+=1;
            else
                repC2[num]+=1;
            //System.out.println("工作关联课程数量="+stu.getEmploymenthistory().getRelevantCourses().size()+ " ,重复课程数量="+num);
        }

//promotion 
        for (StudentProfile stu : sd.getStudentlist()) {
            boolean a;
            for (Employment e1 : stu.getEmploymenthistory().getEmployments()) {
                for (Employment e2 : stu.getEmploymenthistory().getEmployments()) {
                    if (e2.getEmploymentGrade() > e1.getEmploymentGrade()) {
                        a = true;
                    } 
                    else if((e2.getEmploymentGrade() <= e1.getEmploymentGrade())||(e2.getEmploymentGrade()==0&&e1.getEmploymentGrade()==0)){
                        a = false;
                    }
                }
            }
        }
//        Analysis(repC, sd);
        return department;
    }
    
    private void Analysis(StudentDirectory sd) {
        //pieChart
        HashMap<String, Integer> maps1 = new HashMap<>();
        HashMap<String, Integer> maps2 = new HashMap<>();
        for (int i = 0; i < repC1.length; i++) {
            if(repC1[i]!=0){
                 System.out.println(i + " course:"+repC1[i]);
                    maps1.put(i + " course", repC1[i]);    
            }
        }
        System.out.println("-------------");
        for (int i = 0; i < repC2.length; i++) {
            if(repC2[i]!=0){
                System.out.println(i + " course:"+repC2[i]);
                    maps2.put(i + " course", repC2[i]);  
            }
        }
        
//        PieChart_AWT demo = new PieChart_AWT( "Ratio Of Relative Courses Of Rank Top 100 Students",maps );
//        demo.setSize( 560 , 367 );
////        demo.pack();
//        RefineryUtilities.centerFrameOnScreen( demo );
//        demo.setVisible( true );

      PieChart_AWT demo = new PieChart_AWT( "Ratio Of Relative Courses VS Ranks",maps1,maps2 );  
      demo.pack();
      demo.setSize( 1160 , 400 );    
      RefineryUtilities.centerFrameOnScreen( demo );    
      demo.setVisible( true );
      
      //promotion ratio
      int[] r3 = new int[2];
      int[] r4 = new int[2];
      int lengh =  sd.getStudentlist().size();
        for (int i = 0; i < lengh; i++) {
            StudentProfile stu = sd.getStudentlist().get(i);
            if (stu.getEmploymenthistory().isPromotion()) {
                if (i < lengh / 2) {
                    r3[1] += 1;
                } else {
                    r4[1] += 1;
                }
            } else {
                if (i < lengh / 2) {
                    r3[0] += 1;
                } else {
                    r4[0] += 1;
                }

            }
        }
        HashMap<String, Integer> maps3 = new HashMap<>();
        HashMap<String, Integer> maps4 = new HashMap<>();
        maps3.put("True", r3[1]);
        maps3.put("False", r3[0]);
        maps4.put("True", r4[1]);
        maps4.put("False", r4[0]);
      PieChart_AWT demo2 = new PieChart_AWT( "Ratio Of Promotion VS Ranks",maps3,maps4 );  
      demo2.pack();
      demo2.setSize( 1160 , 400 );    
      RefineryUtilities.centerFrameOnScreen( demo2 );    
      demo2.setVisible( true );
        
        //LineChart
        ArrayList<Float> gpas = new ArrayList<>();
        for (StudentProfile stu : sd.getStudentlist()) {
            float gpa = stu.getCurrentGpa();
            gpas.add(gpa);
        }
        //      gpas.add(4.0f);
        LineChart_AWT chart = new LineChart_AWT(
                "Gpa Vs Rank",
                "Gpas vs Ranks",
                gpas,
                "gpa");
        chart.setSize(560,367);
//        chart.pack();
        RefineryUtilities.centerFrameOnScreen(chart);
        chart.setVisible(true);
    }
}
